language: php
php:
  - 5.6
  - 7.0
  #- nightly  # Aka '7'

git:
  depth: 8

install:
  - composer install --prefer-source

script:
  - composer test

after_success:
  #- @echo "Woohoo!"

after_script:
  # (Result: "No such file or directory")
  #- cat /home/travis/build/IET-OU/open-oembed-providers/build/logs/clover.xml

#End.
