language: php
php:
  - 5.6
  - 7.0

git:
  depth: 8

install:
  - composer install

script:
  - composer validate --no-interaction
  - composer test

after_script:
  # (Result: "No such file or directory")
  #- cat /home/travis/build/IET-OU/open-oembed-providers/build/logs/clover.xml

#End.
